In [144]:
import pandas as pd
import json

ruta_archivo_json = 'C:\\Users\\ROXI\\OneDrive\\Escritorio\\Proyecto Individual 1- Data 03- Soy Henry\\Proyecto-Individual-1\\Datasets\\results.json'
datos = pd.read_json(ruta_archivo_json,  lines=True, encoding="utf-8")


In [145]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24960 entries, 0 to 24959
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   resultId         24960 non-null  int64  
 1   raceId           24960 non-null  int64  
 2   driverId         24960 non-null  int64  
 3   constructorId    24960 non-null  int64  
 4   number           24960 non-null  object 
 5   grid             24960 non-null  int64  
 6   position         24960 non-null  object 
 7   positionText     24960 non-null  object 
 8   positionOrder    24960 non-null  int64  
 9   points           24960 non-null  float64
 10  laps             24960 non-null  int64  
 11  time             24960 non-null  object 
 12  milliseconds     24960 non-null  object 
 13  fastestLap       24960 non-null  object 
 14  rank             24960 non-null  object 
 15  fastestLapTime   24960 non-null  object 
 16  fastestLapSpeed  24960 non-null  object 
 17  statusId    

In [146]:
datos

resultId  raceId  driverId  constructorId number  grid position  \
0             1      18         1              1     22     1        1   
1             2      18         2              2      3     5        2   
2             3      18         3              3      7     7        3   
3             4      18         4              4      5    11        4   
4             5      18         5              1     23     3        5   
...         ...     ...       ...            ...    ...   ...      ...   
24955     24961    1047       841             51     99    14       16   
24956     24962    1047       849              3      6    18       17   
24957     24963    1047       825            210     20    20       18   
24958     24964    1047       850            210     51    17       19   
24959     24965    1047       815            211     11    19       \N   

      positionText  positionOrder  points  laps         time milliseconds  \
0                1              1    10.0    58  1:34:50.616      5690616   
1                2              2     8.0    58       +5.478      5696094   
2                3              3     6.0    58       +8.163      5698779   
3                4              4     5.0    58      +17.181      5707797   
4                5              5     4.0    58      +18.014      5708630   
...            ...            ...     ...   ...          ...          ...   
24955           16             16     0.0    54           \N           \N   
24956           17             17     0.0    54           \N           \N   
24957           18             18     0.0    54           \N           \N   
24958           19             19     0.0    53           \N           \N   
24959            R             20     0.0     8           \N           \N   

      fastestLap rank fastestLapTime fastestLapSpeed  statusId  
0             39    2       1:27.452           218.3         1  
1             41    3       1:27.739         217.586         1  
2             41    5       1:28.090         216.719         1  
3             58    7       1:28.603         215.464         1  
4             43    1       1:27.418         218.385         1  
...          ...  ...            ...             ...       ...  
24955         29    7       1:41.675          196.65        11  
24956         49   16       1:42.497         195.073        11  
24957         50   13       1:41.999         196.025        11  
24958         50    8       1:41.707         196.588        12  
24959          6   19       1:43.263         193.625         7  

[24960 rows x 18 columns]

In [201]:
conductor_puntos=datos[datos['driverId']==1]
conductor_puntos["points"].sum()

In [147]:
import numpy as np

In [148]:
datos['position']=datos['position'].replace('\\N',np.nan)

In [149]:
sort_forename=datos['position'].sort_values()
sort_forename.unique()


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., nan])

In [150]:
datos.isnull().sum()

resultId               0
raceId                 0
driverId               0
constructorId          0
number                 0
grid                   0
position           10735
positionText           0
positionOrder          0
points                 0
laps                   0
time                   0
milliseconds           0
fastestLap             0
rank                   0
fastestLapTime         0
fastestLapSpeed        0
statusId               0
dtype: int64

hay muchos valores faltantes 

In [151]:
sort_forename=datos['positionOrder'].sort_values()
sort_forename.unique()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39], dtype=int64)

In [152]:
sort_forename.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39], dtype=int64)

In [153]:
conductor=datos[datos['driverId']==851]

In [154]:
conductor

resultId  raceId  driverId  constructorId number  grid  position  \
24935     24941    1046       851              3     89    17      16.0   

      positionText  positionOrder  points  laps     time milliseconds  \
24935           16             16     0.0    87  +33.674      5508788   

      fastestLap rank fastestLapTime fastestLapSpeed  statusId  
24935         56   15       0:57.392          222.24         1

In [120]:
cantidad_de_veces=primera_posicion['positionOrder'].count()

In [155]:
datos.to_csv('result_.csv', encoding='utf-8', index=False)

In [110]:
array_conductor=datos['driverId'].sort_values()
array_conductor=array_conductor.unique()

In [111]:
array_conductor=array_conductor.unique()

In [112]:
array_conductor

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [ ]:
datos[datos['positionOrder']==1]

In [173]:
auxiliar=0
auxiliar_conductor=0
for indice,conductor in enumerate(array_conductor) :
   conductor_df=datos[datos['positionOrder']==conductor]
   primera_posicion=conductor_df[conductor_df['positionOrder']==1]
   cantidad_de_veces=primera_posicion['positionOrder'].count()
   if(cantidad_de_veces>auxiliar):
      auxiliar=cantidad_de_veces
      auxiliar_conductor=conductor


In [174]:
print(auxiliar)

1038


In [127]:
print(auxiliar_conductor)

1


Piloto con mayor cantidad de primeros puestos

In [36]:
import pandas as pd
import numpy as np
    
datos_df=pd.read_csv(r'C:\Users\ROXI\OneDrive\Escritorio\Proyecto Individual 1- Data 03- Soy Henry\Proyecto-Individual-1\Datasets\pandas\dataset_procesados\result_.csv',encoding='utf-8-sig')
datos_df_1=pd.read_csv(r'C:\Users\ROXI\OneDrive\Escritorio\Proyecto Individual 1- Data 03- Soy Henry\Proyecto-Individual-1\Datasets\pandas\dataset_procesados\drivers_.csv',encoding='utf-8-sig')

array_conductor=datos_df['driverId'].sort_values()
array_conductor=array_conductor.unique()

auxiliar=0
auxiliar_conductor=0
for indice,conductor in enumerate(array_conductor) :
    conductor_df=datos_df[datos_df['positionOrder']==conductor]
    primera_posicion=conductor_df[conductor_df['positionOrder']==1]
    cantidad_de_veces=primera_posicion['positionOrder'].count()
    if(cantidad_de_veces>auxiliar):
        auxiliar=cantidad_de_veces
        auxiliar_conductor=conductor

print(auxiliar)
print(auxiliar_conductor)

conductor_df_1=datos_df_1[datos_df_1['driverId']==auxiliar_conductor]
forename=conductor_df_1["forename"].iloc[0]
surname=conductor_df_1["surname"].iloc[0]

1038
1


In [38]:
forenamestr = str(forename)
forenamestr

'lewis'

In [37]:
forename

'lewis'

In [216]:
datos_df=pd.read_csv(r'C:\Users\ROXI\OneDrive\Escritorio\Proyecto Individual 1- Data 03- Soy Henry\Proyecto-Individual-1\Datasets\pandas\dataset_procesados\result_.csv',encoding='utf-8-sig')
datos_df_1=pd.read_csv(r'C:\Users\ROXI\OneDrive\Escritorio\Proyecto Individual 1- Data 03- Soy Henry\Proyecto-Individual-1\Datasets\pandas\dataset_procesados\drivers_.csv',encoding='utf-8-sig')

In [2]:
import pandas as pd

datos_df=pd.read_csv(r'C:\Users\ROXI\OneDrive\Escritorio\Proyecto Individual 1- Data 03- Soy Henry\Proyecto-Individual-1\Datasets\pandas\dataset_procesados\result_.csv',encoding='utf-8-sig')
datos_df_1=pd.read_csv(r'C:\Users\ROXI\OneDrive\Escritorio\Proyecto Individual 1- Data 03- Soy Henry\Proyecto-Individual-1\Datasets\pandas\dataset_procesados\drivers_.csv',encoding='utf-8-sig')

pilotos=datos_df_1[(datos_df_1['nationality'] == "american") | (datos_df_1['nationality'] == "british")]
conductor_american_british=pilotos["driverId"].values

In [3]:
import pandas as pd
pilotos=datos_df_1[(datos_df_1['nationality'] == "american") | (datos_df_1['nationality'] == "british")]
conductor_american_british=pilotos["driverId"].values

auxiliar=0
auxiliar_conductor=0
for indice,conductor in enumerate(conductor_american_british):
    conductor_puntos=datos_df[datos_df['points']==conductor]
    
    conductor_puntos_cantidad=conductor_puntos["points"].sum()
    if(conductor_puntos_cantidad>auxiliar):
        auxiliar=conductor_puntos_cantidad
        auxiliar_conductor=conductor

print(auxiliar)
print(auxiliar_conductor)       


3762.0
18


In [8]:
name_driver=datos_df_1[datos_df_1['driverId'] == auxiliar_conductor]

In [9]:
name_driver[["forename",	"surname"]]

forename surname
17   jenson  button